<a href="https://colab.research.google.com/github/nitishjoshi86/PythonNum/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch

SEED = 1234

#set seed for reproducibility

np.random.seed(seed = SEED)
torch.manual_seed(SEED)

In [2]:
#creating a random tensor

x = torch.randn(2,3) #normal distribution (rand(2,3) -> uniform distribution)
print(f"Type: {x.type()}")
print(f"Size: {x.shape}")
print(f"Values: \n {x}")

Type: torch.FloatTensor
Size: torch.Size([2, 3])
Values: 
 tensor([[ 0.0461,  0.4024, -1.0115],
        [ 0.2167, -0.6123,  0.5036]])


In [3]:
#zero and ones tensor

x = torch.zeros(2,3)
print(x)
x = torch.ones(2,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [4]:
#list -> tensor

x = torch.Tensor([[1,2,3], [4,5,6]])
print(f"Size: {x.shape}")
print(f"Value: \n {x}")

Size: torch.Size([2, 3])
Value: 
 tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [5]:
#numpy array -> tensor

x = torch.Tensor(np.random.rand(2,3))
print(f"Size: {x.shape}")
print(f"value: \n {x}")

Size: torch.Size([2, 3])
value: 
 tensor([[0.1915, 0.6221, 0.4377],
        [0.7854, 0.7800, 0.2726]])


In [6]:
#changing tensor type

x = torch.Tensor(3,4)
print(f"Type: {x.type()}")
x = x.long()
print(f"Type: {x.type()}")

Type: torch.FloatTensor
Type: torch.LongTensor


In [14]:
#basic operations with tensors

#addition

x = torch.randn(2,3)
y = torch.randn(2,3)
z = x + y
print('addition')
print(f"Size: {z.shape}")
print(f"Values: \n{z}")

#dotproduct

x = torch.randn(2,3)
y = torch.randn(3,2)
z = torch.mm(x, y)
print('dotproduct')
print(f"Size: {z.shape}")
print(f"Values: \n{z}")

#transpose

x = torch.randn(2,3)
print('transpose')
print(f"Size: {x.shape}")
print(f"Values: \n{x}")
y = torch.t(x)
print(f"Size: {y.shape}")
print(f"Values: \n{y}")

addition
Size: torch.Size([2, 3])
Values: 
tensor([[-0.5583, -0.4106, -0.3145],
        [ 1.3800,  0.3692,  1.2036]])
dotproduct
Size: torch.Size([2, 2])
Values: 
tensor([[2.3773, 4.3214],
        [0.6758, 2.3792]])
transpose
Size: torch.Size([2, 3])
Values: 
tensor([[ 0.1438, -1.5399,  0.1169],
        [-0.1423,  0.1624,  0.4570]])
Size: torch.Size([3, 2])
Values: 
tensor([[ 0.1438, -0.1423],
        [-1.5399,  0.1624],
        [ 0.1169,  0.4570]])


In [15]:
#reshape

x = torch.randn(2,3)
z = x.view(3,2)
print(f"size: {z.shape}")
print(f"value: \n {z}")

size: torch.Size([3, 2])
value: 
 tensor([[ 1.1839,  0.8176],
        [ 0.7177, -1.3875],
        [-0.5130,  0.3247]])


In [16]:
# Dangers of reshaping (unintended consequences)
x = torch.tensor([
    [[1,1,1,1], [2,2,2,2], [3,3,3,3]],
    [[10,10,10,10], [20,20,20,20], [30,30,30,30]]
])
print(f"Size: {x.shape}")
print(f"x: \n{x}\n")

a = x.view(x.size(1), -1)
print(f"\nSize: {a.shape}")
print(f"a: \n{a}\n")

b = x.transpose(0,1).contiguous()
print(f"\nSize: {b.shape}")
print(f"b: \n{b}\n")

c = b.view(b.size(0), -1)
print(f"\nSize: {c.shape}")
print(f"c: \n{c}")

Size: torch.Size([2, 3, 4])
x: 
tensor([[[ 1,  1,  1,  1],
         [ 2,  2,  2,  2],
         [ 3,  3,  3,  3]],

        [[10, 10, 10, 10],
         [20, 20, 20, 20],
         [30, 30, 30, 30]]])


Size: torch.Size([3, 8])
a: 
tensor([[ 1,  1,  1,  1,  2,  2,  2,  2],
        [ 3,  3,  3,  3, 10, 10, 10, 10],
        [20, 20, 20, 20, 30, 30, 30, 30]])


Size: torch.Size([3, 2, 4])
b: 
tensor([[[ 1,  1,  1,  1],
         [10, 10, 10, 10]],

        [[ 2,  2,  2,  2],
         [20, 20, 20, 20]],

        [[ 3,  3,  3,  3],
         [30, 30, 30, 30]]])


Size: torch.Size([3, 8])
c: 
tensor([[ 1,  1,  1,  1, 10, 10, 10, 10],
        [ 2,  2,  2,  2, 20, 20, 20, 20],
        [ 3,  3,  3,  3, 30, 30, 30, 30]])


In [17]:
#dimensional operations

x = torch.randn(2,3)
print(f"values: \n{x}")
y = torch.sum(y, dim = 0)
print(f"values: \n{y}")
z = torch.sum(z, dim = 1)
print(f"values: \n{z}")

values: 
tensor([[ 0.4834, -0.5761, -0.5541],
        [ 1.4976, -0.4817, -1.4194]])
values: 
tensor([-1.2791,  0.4772])
values: 
tensor([ 2.0016, -0.6698, -0.1883])


In [18]:
#how to extract separate and join values from our tensors

x = torch.randn(3,4)
print(f"x: \n {x}")
print(f"x[:1]: \n{x[:1]}")
print(f"x[:1, 1:3]: \n{x[:1, 1:3]}")

x: 
 tensor([[-0.4455, -0.4108,  0.3571, -1.4713],
        [ 0.9365,  0.2561, -0.3379,  0.1182],
        [-0.8526,  0.4603,  0.9020,  0.9087]])
x[:1]: 
tensor([[-0.4455, -0.4108,  0.3571, -1.4713]])
x[:1, 1:3]: 
tensor([[-0.4108,  0.3571]])


In [20]:
#slicing, select with dimensional indicies

x = torch.randn(2,3)
print(f"value: \n {x}")

colindices = torch.LongTensor([0,2])
choosen = torch.index_select(x, dim =1, index = colindices)#values from column 0 n 2
print(f"values: \n {choosen}")

rowindices = torch.LongTensor([0,1])
colindices = torch.LongTensor([0,2])
chosen = x[rowindices, colindices] #values from (0,0) & (2,1)
print(f"values: \n{choosen}")

value: 
 tensor([[ 0.6744,  1.0753,  0.1647],
        [ 0.2463, -0.2627, -0.5241]])
values: 
 tensor([[ 0.6744,  0.1647],
        [ 0.2463, -0.5241]])
values: 
tensor([[ 0.6744,  0.1647],
        [ 0.2463, -0.5241]])


In [21]:
#joining, concatenation

x = torch.randn(2,3)
print(f"values: \n{x}")
y = torch.cat([x,x], dim = 0) #stack by rows(dim = 1 to stack by columns)
print(f"values: \n{y}")

values: 
tensor([[-0.0901,  1.1621,  1.5299],
        [ 0.7377, -1.4209,  0.0663]])
values: 
tensor([[-0.0901,  1.1621,  1.5299],
        [ 0.7377, -1.4209,  0.0663],
        [-0.0901,  1.1621,  1.5299],
        [ 0.7377, -1.4209,  0.0663]])


In [22]:
#tensors with gradient bookkeeping

x = torch.rand(3, 4, requires_grad= True)
y = 3*x + 2
z = y.mean()
z.backward() #z has to be scalar

print(f"x: \n{x}")
print(f"x.grad: \n{x.grad}")

x: 
tensor([[0.5462, 0.3548, 0.4695, 0.9934],
        [0.5161, 0.3650, 0.5073, 0.2586],
        [0.2099, 0.3873, 0.7590, 0.4613]], requires_grad=True)
x.grad: 
tensor([[0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500]])


In [23]:
#cuda

print(torch.cuda.is_available())

False


In [24]:
import torch

In [25]:
print(torch.cuda.is_available())

False


In [26]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print (device)

cpu


In [27]:
x = torch.rand(2,3)
print (x.is_cuda)
x = torch.rand(2,3).to(device) # sTensor is stored on the GPU
print (x.is_cuda)

False
False
